### ISSUE TITLE
Enable-Python breaks if $Env:PYTHONHOME exists

### ISSUE THREAD

**Issue by travisclagrone** [DavidWhittingham/ps-EnablePython#2]
If a valid `$Env:PYTHONHOME` exists, then invoking `Enable-Python -Version $v` (where `$v` is a valid python version other than the one referred to by `$Env:PYTHONHOME`) will cause subsequent invocations of `python` (where a Python module or package is accessed) to error out.

### Given

```none
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Microsoft Windows 10.0.17763 
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


PS> Get-Module -Name 'EnablePython'

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.0.2      EnablePython                        {Disable-Python, Enable-Python, Get-Python}


PS> Get-Command -Name 'python'

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     python.exe                                         3.7.3150.… C:\Users\Travis.C.LaGrone\AppData\Local\Programs\Python\Python37\python.exe


PS> python -m pip --version
pip 19.1.1 from C:\Users\Travis.C.LaGrone\AppData\Local\Programs\Python\Python37\lib\site-packages\pip (python 3.7)
```

### When

```powershell
$Env:PYTHONHOME = Get-Command -Name 'python' | Select-Object -ExpandProperty 'Path'

EnablePython\Enable-Python -Version 3.6

python -m pip --version
```

### Expected behavior

```none
pip 18.1 from C:\Users\Travis.C.LaGrone\AppData\Local\Programs\Python\Python36\lib\site-packages\pip (python 3.6)
```

### Actual behavior

```none
Failed to import the site module
Traceback (most recent call last):
  File "C:\Users\Travis.C.LaGrone\AppData\Local\Programs\Python\Python37\lib\site.py", line 586, in <module>
    main()
  File "C:\Users\Travis.C.LaGrone\AppData\Local\Programs\Python\Python37\lib\site.py", line 573, in main
    known_paths = addsitepackages(known_paths)
  File "C:\Users\Travis.C.LaGrone\AppData\Local\Programs\Python\Python37\lib\site.py", line 349, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "C:\Users\Travis.C.LaGrone\AppData\Local\Programs\Python\Python37\lib\site.py", line 207, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "C:\Users\Travis.C.LaGrone\AppData\Local\Programs\Python\Python37\lib\site.py", line 159, in addpackage
    f = open(fullname, "r")
  File "C:\Users\Travis.C.LaGrone\AppData\Local\Programs\Python\Python37\lib\_bootlocale.py", line 12, in getpreferredencoding
    if sys.flags.utf8_mode:
AttributeError: 'sys.flags' object has no attribute 'utf8_mode'
```

## Related Issues

- [getPythonVersion breaks if $Env:PYTHONHOME exists](#1)

## Suggested Fix

All of the following:

- `Enable-Python` checks if `$Env:PYTHONHOME` exists, and if so persists the value of `$Env:PYTHONHOME` and then sets `$Env:PYTHONHOME` to the path of the parent directory of the enabled python executable.
- `Disable-Python` checks if the prior value of `$Env:PYTHONHOME` has been persisted, and if so sets `$Env:PYTHONHOME` to the persisted value and then clears the persisted value, but otherwise clears `$Env:PYTHONHOME` (if any).

Or in terms of behavioral outcomes:

- Preserve the value (including null) of `$Env:PYTHONHOME` across any sequence of zero or more `Enable-Python` invocations followed by one or more `Disable-Python` invocations.
- Upon invoking `Enable-Python`, set `$Env:PYTHONHOME` to the home of the enabled python if and only if `$Env:PYTHONHOME` was already set.

**Comment by DavidWhittingham** [comment]
@travis-c-lagrone Seems slightly overkill, this thing isn't trying to prevent people from shooting themselves in the foot (i.e. having `$env:PYTHONHOME` set to a value that doesn't make sense).  That being said, it should be fairly trivial to implement that behaviour, I'll look at it tomorrow.

Would it not be better to simply set `$env:PYTHONHOME` to null in the event that it has a value, and restore on `Disable-Python`, rather than being explicit (i.e. leave it up to the Python implementation's default behaviour, rather than providing a value)?

**Comment by travisclagrone** [comment]
That sounds like an eminently reasonable design to me.  I would still push for at least an opt-in switch to set `$Env:PYTHONHOME` to the new target upon invoking `Enable-Python`.  My use case for this is testing system-level scripts/tools for multiple versions and across multiple scopes, and so I'm embedding a reference to `$Env:PYTHONHOME` in several other environment variables as a way to efficiently/modularly change an entire set of environment configurations together.  I can always script it out the long way of course (which is what I have been doing _ad hoc_ to-date), but I really like what you've done with `Get-Python` and the way `Enable-Python`/`Disable-Python` can synergize with it, and I'd like to build off your work if possible.

**Comment by DavidWhittingham** [comment]
@travis-c-lagrone I really don't want to change the default behaviour of any particular Python implementation and try to guess an appropriate `$Env:PYTHONHOME`, that seems frought with risk.

That being said, would it suit your needs if I make an optional parameter that allows a user to specifiy a custom value for `$Env:PYTHONHOME` when you call `Enable-Python`, e.g. `Enable-Python 3.6 -Home "path/to/custom/home"`?  That would be easy, and would fallback to `$null` in the event nothing is passed in, which fits in well with my earlier suggested workflow.

**Comment by DavidWhittingham** [comment]
@travis-c-lagrone I've implemented what I described above on the develop branch, let me know if this solution works for you.

**Comment by DavidWhittingham** [comment]
@travis-c-lagrone I have merged the changes into master and pushed a release (v2.1.0).  If you have any further concerns or questions, let me know in the next 24 hours, otherwise I'll go ahead and close off this issue.

**Comment by travisclagrone** [comment]
My apologies for the delay.  I was traveling and away from my work laptop for the past several days.

This looks great.  Thank you very much for the changes!
